USE [master]
GO

/****** Object:  Database [Rapture]    Script Date: 4/6/2023 4:05:14 PM ******/
CREATE DATABASE [Rapture]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Rapture', FILENAME = N'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\Rapture.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Rapture_log', FILENAME = N'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\Rapture_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Rapture].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Rapture] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Rapture] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Rapture] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Rapture] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Rapture] SET ARITHABORT OFF 
GO

ALTER DATABASE [Rapture] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Rapture] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Rapture] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Rapture] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Rapture] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Rapture] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Rapture] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Rapture] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Rapture] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Rapture] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Rapture] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Rapture] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Rapture] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Rapture] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Rapture] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Rapture] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Rapture] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Rapture] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Rapture] SET  MULTI_USER 
GO

ALTER DATABASE [Rapture] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Rapture] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Rapture] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Rapture] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Rapture] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Rapture] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Rapture] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Rapture] SET  READ_WRITE 
GO

